name: library_booking
publish_to: 'none'
description: Library Booking — Borrow & Return (Flutter 3.24+, Riverpod, Dio, Hive)
version: 0.1.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # UI/UX
  awesome_dialog: ^3.2.0
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  intl: ^0.19.0

  # State & routing
  flutter_riverpod: ^2.5.1
  riverpod: ^2.5.1
  go_router: ^14.2.0

  # Networking
  dio: ^5.6.0
  dio_smart_retry: ^6.0.0

  # Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Mock server (ต้องอยู่ใน dependencies เพื่อให้ dart run tool/mock_server.dart ใช้ได้)
  shelf: ^1.4.1
  shelf_router: ^1.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mocktail: ^1.0.3

flutter:
  uses-material-design: true
